name: example
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_nodelistview:
    path: ..

flutter:
  uses-material-design: true
